PLUGIN = null${PLUGIN_SUFFIX}

SRCS = null.c

include ../../buildsys.mk
include ../../extra.mk

plugindir := ${plugindir}/${OUTPUT_PLUGIN_DIR}

CPPFLAGS += ${GTK_CFLAGS}   -I../..
LIBS += ${GTK_LIBS}
