#ifndef AUDACIOUS_PLUGINS_WINDOWS_KEY_STRINGS_HPP
#define AUDACIOUS_PLUGINS_WINDOWS_KEY_STRINGS_HPP

// https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
// As defined in WinUser.h

constexpr const char *const WIN_VK_NAMES[] = {
    "UNKNOWN_KEY: 0",
    "LBUTTON",
    "RBUTTON",
    "Scroll Lock",
    "MBUTTON",
    "XBUTTON1",
    "XBUTTON2",
    "UNKNOWN_KEY: 7",
    "Backspace",
    "Tab",
    "UNKNOWN_KEY: 10",
    "UNKNOWN_KEY: 11",
    "CLEAR",
    "Enter",
    "UNKNOWN_KEY: 14",
    "UNKNOWN_KEY: 15",
    "Shift",
    "Ctrl",
    "Alt",
    "PAUSE",
    "Caps Lock",
    "KANA",
    "UNKNOWN_KEY: 22",
    "JUNJA",
    "FINAL",
    "HANJA",
    "UNKNOWN_KEY: 26",
    "Esc",
    "CONVERT",
    "NONCONVERT",
    "ACCEPT",
    "MODECHANGE",
    "Space",
    "Page Up",
    "Page Down",
    "End",
    "Home",
    "Left",
    "Up",
    "Right",
    "Down",
    "SELECT",
    "PRINT",
    "EXECUTE",
    "SNAPSHOT",
    "Insert",
    "Delete",
    "HELP",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "UNKNOWN_KEY: 58",
    "UNKNOWN_KEY: 59",
    "UNKNOWN_KEY: 60",
    "UNKNOWN_KEY: 61",
    "UNKNOWN_KEY: 62",
    "UNKNOWN_KEY: 63",
    "UNKNOWN_KEY: 64",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "LWIN",
    "RWIN",
    "APPS",
    "UNKNOWN_KEY: 94",
    "SLEEP",
    "Num 0",
    "Num 1",
    "Num 2",
    "Num 3",
    "Num 4",
    "Num 5",
    "Num 6",
    "Num 7",
    "Num 8",
    "Num 9",
    "Num *",
    "Num +",
    "UNKNOWN_KEY: 108",
    "Num -",
    "Num Del",
    "Num /",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",
    "NAVIGATION_VIEW",
    "NAVIGATION_MENU",
    "NAVIGATION_UP",
    "NAVIGATION_DOWN",
    "NAVIGATION_LEFT",
    "NAVIGATION_RIGHT",
    "NAVIGATION_ACCEPT",
    "NAVIGATION_CANCEL",
    "Num Lock",
    "Scroll Lock",
    "OEM_NEC_EQUAL",
    "OEM_FJ_MASSHOU",
    "OEM_FJ_TOUROKU",
    "OEM_FJ_LOYA",
    "OEM_FJ_ROYA",
    "UNKNOWN_KEY: 151",
    "UNKNOWN_KEY: 152",
    "UNKNOWN_KEY: 153",
    "UNKNOWN_KEY: 154",
    "UNKNOWN_KEY: 155",
    "UNKNOWN_KEY: 156",
    "UNKNOWN_KEY: 157",
    "UNKNOWN_KEY: 158",
    "UNKNOWN_KEY: 159",
    "Left Shift",
    "Right Shift",
    "Left Ctrl",
    "Right Control",
    "Left Alt",
    "Right Alt",
    "BROWSER_BACK",
    "BROWSER_FORWARD",
    "BROWSER_REFRESH",
    "BROWSER_STOP",
    "BROWSER_SEARCH",
    "BROWSER_FAVORITES",
    "BROWSER_HOME",
    "VOLUME_MUTE",
    "VOLUME_DOWN",
    "VOLUME_UP",
    "MEDIA_NEXT_TRACK",
    "MEDIA_PREV_TRACK",
    "MEDIA_STOP",
    "MEDIA_PLAY_PAUSE",
    "LAUNCH_MAIL",
    "LAUNCH_MEDIA_SELECT",
    "LAUNCH_APP1",
    "LAUNCH_APP2",
    "UNKNOWN_KEY: 184",
    "UNKNOWN_KEY: 185",
    "OEM_1",
    "OEM_PLUS",
    "OEM_COMMA",
    "OEM_MINUS",
    "OEM_PERIOD",
    "OEM_2",
    "OEM_3",
    "UNKNOWN_KEY: 193",
    "F15",
    "GAMEPAD_A",
    "GAMEPAD_B",
    "GAMEPAD_X",
    "GAMEPAD_Y",
    "GAMEPAD_RIGHT_SHOULDER",
    "GAMEPAD_LEFT_SHOULDER",
    "GAMEPAD_LEFT_TRIGGER",
    "GAMEPAD_RIGHT_TRIGGER",
    "GAMEPAD_DPAD_UP",
    "GAMEPAD_DPAD_DOWN",
    "GAMEPAD_DPAD_LEFT",
    "GAMEPAD_DPAD_RIGHT",
    "GAMEPAD_MENU",
    "GAMEPAD_VIEW",
    "GAMEPAD_LEFT_THUMBSTICK_BUTTON",
    "GAMEPAD_RIGHT_THUMBSTICK_BUTTON",
    "GAMEPAD_LEFT_THUMBSTICK_UP",
    "GAMEPAD_LEFT_THUMBSTICK_DOWN",
    "GAMEPAD_LEFT_THUMBSTICK_RIGHT",
    "GAMEPAD_LEFT_THUMBSTICK_LEFT",
    "GAMEPAD_RIGHT_THUMBSTICK_UP",
    "GAMEPAD_RIGHT_THUMBSTICK_DOWN",
    "GAMEPAD_RIGHT_THUMBSTICK_RIGHT",
    "GAMEPAD_RIGHT_THUMBSTICK_LEFT",
    "OEM_4",
    "OEM_5",
    "OEM_6",
    "OEM_7",
    "OEM_8",
    "UNKNOWN_KEY: 224",
    "OEM_AX",
    "OEM_102",
    "ICO_HELP",
    "ICO_00",
    "PROCESSKEY",
    "ICO_CLEAR",
    "PACKET",
    "UNKNOWN_KEY: 232",
    "OEM_RESET",
    "OEM_JUMP",
    "OEM_PA1",
    "OEM_PA2",
    "OEM_PA3",
    "OEM_WSCTRL",
    "OEM_CUSEL",
    "OEM_ATTN",
    "OEM_FINISH",
    "OEM_COPY",
    "OEM_AUTO",
    "OEM_ENLW",
    "OEM_BACKTAB",
    "ATTN",
    "CRSEL",
    "EXSEL",
    "EREOF",
    "PLAY",
    "ZOOM",
    "NONAME",
    "PA1",
    "OEM_CLEAR",
    "UNKNOWN_KEY: 255"
};

#endif //AUDACIOUS_PLUGINS_WINDOWS_KEY_STRINGS_HPP
