/*
 * Generated by gdbus-codegen 2.30.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "object-core.h"

#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        ret = (g_value_get_double (a) == g_value_get_double (b));
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.mpris.MediaPlayer2
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:MprisMediaPlayer2
 * @title: MprisMediaPlayer2
 * @short_description: Generated C code for the org.mpris.MediaPlayer2 D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-mpris-MediaPlayer2.top_of_page">org.mpris.MediaPlayer2</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.mpris.MediaPlayer2 ---- */

static const _ExtendedGDBusMethodInfo _mpris_media_player2_method_info_quit =
{
  {
    -1,
    "Quit",
    NULL,
    NULL,
    NULL
  },
  "handle-quit",
  FALSE
};

static const _ExtendedGDBusMethodInfo _mpris_media_player2_method_info_raise =
{
  {
    -1,
    "Raise",
    NULL,
    NULL,
    NULL
  },
  "handle-raise",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _mpris_media_player2_method_info_pointers[] =
{
  &_mpris_media_player2_method_info_quit,
  &_mpris_media_player2_method_info_raise,
  NULL
};

static const _ExtendedGDBusPropertyInfo _mpris_media_player2_property_info_can_quit =
{
  {
    -1,
    "CanQuit",
    "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "can-quit",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _mpris_media_player2_property_info_can_raise =
{
  {
    -1,
    "CanRaise",
    "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "can-raise",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _mpris_media_player2_property_info_desktop_entry =
{
  {
    -1,
    "DesktopEntry",
    "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "desktop-entry",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _mpris_media_player2_property_info_has_track_list =
{
  {
    -1,
    "HasTrackList",
    "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "has-track-list",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _mpris_media_player2_property_info_identity =
{
  {
    -1,
    "Identity",
    "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "identity",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _mpris_media_player2_property_info_pointers[] =
{
  &_mpris_media_player2_property_info_can_quit,
  &_mpris_media_player2_property_info_can_raise,
  &_mpris_media_player2_property_info_desktop_entry,
  &_mpris_media_player2_property_info_has_track_list,
  &_mpris_media_player2_property_info_identity,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _mpris_media_player2_interface_info =
{
  {
    -1,
    "org.mpris.MediaPlayer2",
    (GDBusMethodInfo **) &_mpris_media_player2_method_info_pointers,
    NULL,
    (GDBusPropertyInfo **) &_mpris_media_player2_property_info_pointers,
    NULL
  },
  "media-player2",
};


/**
 * mpris_media_player2_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-mpris-MediaPlayer2.top_of_page">org.mpris.MediaPlayer2</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
mpris_media_player2_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_mpris_media_player2_interface_info;
}

/**
 * mpris_media_player2_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #MprisMediaPlayer2 interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
mpris_media_player2_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "can-quit");
  g_object_class_override_property (klass, property_id_begin++, "can-raise");
  g_object_class_override_property (klass, property_id_begin++, "desktop-entry");
  g_object_class_override_property (klass, property_id_begin++, "has-track-list");
  g_object_class_override_property (klass, property_id_begin++, "identity");
  return property_id_begin - 1;
}



/**
 * MprisMediaPlayer2:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-mpris-MediaPlayer2.top_of_page">org.mpris.MediaPlayer2</link>.
 */

/**
 * MprisMediaPlayer2Iface:
 * @parent_iface: The parent interface.
 * @handle_quit: Handler for the #MprisMediaPlayer2::handle-quit signal.
 * @handle_raise: Handler for the #MprisMediaPlayer2::handle-raise signal.
 * @get_can_quit: Getter for the #MprisMediaPlayer2:can-quit property.
 * @get_can_raise: Getter for the #MprisMediaPlayer2:can-raise property.
 * @get_desktop_entry: Getter for the #MprisMediaPlayer2:desktop-entry property.
 * @get_has_track_list: Getter for the #MprisMediaPlayer2:has-track-list property.
 * @get_identity: Getter for the #MprisMediaPlayer2:identity property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-mpris-MediaPlayer2.top_of_page">org.mpris.MediaPlayer2</link>.
 */

static void
mpris_media_player2_default_init (MprisMediaPlayer2Iface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * MprisMediaPlayer2::handle-quit:
   * @object: A #MprisMediaPlayer2.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-mpris-MediaPlayer2.Quit">Quit()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call mpris_media_player2_complete_quit() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-quit",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (MprisMediaPlayer2Iface, handle_quit),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * MprisMediaPlayer2::handle-raise:
   * @object: A #MprisMediaPlayer2.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-mpris-MediaPlayer2.Raise">Raise()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call mpris_media_player2_complete_raise() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-raise",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (MprisMediaPlayer2Iface, handle_raise),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /* GObject properties for D-Bus properties: */
  /**
   * MprisMediaPlayer2:can-quit:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-mpris-MediaPlayer2.CanQuit">"CanQuit"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("can-quit", "CanQuit", "CanQuit", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * MprisMediaPlayer2:can-raise:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-mpris-MediaPlayer2.CanRaise">"CanRaise"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("can-raise", "CanRaise", "CanRaise", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * MprisMediaPlayer2:desktop-entry:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-mpris-MediaPlayer2.DesktopEntry">"DesktopEntry"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("desktop-entry", "DesktopEntry", "DesktopEntry", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * MprisMediaPlayer2:has-track-list:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-mpris-MediaPlayer2.HasTrackList">"HasTrackList"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("has-track-list", "HasTrackList", "HasTrackList", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * MprisMediaPlayer2:identity:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-mpris-MediaPlayer2.Identity">"Identity"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("identity", "Identity", "Identity", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

typedef MprisMediaPlayer2Iface MprisMediaPlayer2Interface;
G_DEFINE_INTERFACE (MprisMediaPlayer2, mpris_media_player2, G_TYPE_OBJECT);

/**
 * mpris_media_player2_get_can_quit: (skip)
 * @object: A #MprisMediaPlayer2.
 *
 * Gets the value of the <link linkend="gdbus-property-org-mpris-MediaPlayer2.CanQuit">"CanQuit"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
mpris_media_player2_get_can_quit (MprisMediaPlayer2 *object)
{
  return MPRIS_MEDIA_PLAYER2_GET_IFACE (object)->get_can_quit (object);
}

/**
 * mpris_media_player2_set_can_quit: (skip)
 * @object: A #MprisMediaPlayer2.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-mpris-MediaPlayer2.CanQuit">"CanQuit"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
mpris_media_player2_set_can_quit (MprisMediaPlayer2 *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "can-quit", value, NULL);
}

/**
 * mpris_media_player2_get_can_raise: (skip)
 * @object: A #MprisMediaPlayer2.
 *
 * Gets the value of the <link linkend="gdbus-property-org-mpris-MediaPlayer2.CanRaise">"CanRaise"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
mpris_media_player2_get_can_raise (MprisMediaPlayer2 *object)
{
  return MPRIS_MEDIA_PLAYER2_GET_IFACE (object)->get_can_raise (object);
}

/**
 * mpris_media_player2_set_can_raise: (skip)
 * @object: A #MprisMediaPlayer2.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-mpris-MediaPlayer2.CanRaise">"CanRaise"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
mpris_media_player2_set_can_raise (MprisMediaPlayer2 *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "can-raise", value, NULL);
}

/**
 * mpris_media_player2_get_desktop_entry: (skip)
 * @object: A #MprisMediaPlayer2.
 *
 * Gets the value of the <link linkend="gdbus-property-org-mpris-MediaPlayer2.DesktopEntry">"DesktopEntry"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use mpris_media_player2_dup_desktop_entry() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
mpris_media_player2_get_desktop_entry (MprisMediaPlayer2 *object)
{
  return MPRIS_MEDIA_PLAYER2_GET_IFACE (object)->get_desktop_entry (object);
}

/**
 * mpris_media_player2_dup_desktop_entry: (skip)
 * @object: A #MprisMediaPlayer2.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-mpris-MediaPlayer2.DesktopEntry">"DesktopEntry"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
mpris_media_player2_dup_desktop_entry (MprisMediaPlayer2 *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "desktop-entry", &value, NULL);
  return value;
}

/**
 * mpris_media_player2_set_desktop_entry: (skip)
 * @object: A #MprisMediaPlayer2.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-mpris-MediaPlayer2.DesktopEntry">"DesktopEntry"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
mpris_media_player2_set_desktop_entry (MprisMediaPlayer2 *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "desktop-entry", value, NULL);
}

/**
 * mpris_media_player2_get_has_track_list: (skip)
 * @object: A #MprisMediaPlayer2.
 *
 * Gets the value of the <link linkend="gdbus-property-org-mpris-MediaPlayer2.HasTrackList">"HasTrackList"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
mpris_media_player2_get_has_track_list (MprisMediaPlayer2 *object)
{
  return MPRIS_MEDIA_PLAYER2_GET_IFACE (object)->get_has_track_list (object);
}

/**
 * mpris_media_player2_set_has_track_list: (skip)
 * @object: A #MprisMediaPlayer2.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-mpris-MediaPlayer2.HasTrackList">"HasTrackList"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
mpris_media_player2_set_has_track_list (MprisMediaPlayer2 *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "has-track-list", value, NULL);
}

/**
 * mpris_media_player2_get_identity: (skip)
 * @object: A #MprisMediaPlayer2.
 *
 * Gets the value of the <link linkend="gdbus-property-org-mpris-MediaPlayer2.Identity">"Identity"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use mpris_media_player2_dup_identity() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
mpris_media_player2_get_identity (MprisMediaPlayer2 *object)
{
  return MPRIS_MEDIA_PLAYER2_GET_IFACE (object)->get_identity (object);
}

/**
 * mpris_media_player2_dup_identity: (skip)
 * @object: A #MprisMediaPlayer2.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-mpris-MediaPlayer2.Identity">"Identity"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
mpris_media_player2_dup_identity (MprisMediaPlayer2 *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "identity", &value, NULL);
  return value;
}

/**
 * mpris_media_player2_set_identity: (skip)
 * @object: A #MprisMediaPlayer2.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-mpris-MediaPlayer2.Identity">"Identity"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
mpris_media_player2_set_identity (MprisMediaPlayer2 *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "identity", value, NULL);
}

/**
 * mpris_media_player2_call_quit:
 * @proxy: A #MprisMediaPlayer2Proxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2.Quit">Quit()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mpris_media_player2_call_quit_finish() to get the result of the operation.
 *
 * See mpris_media_player2_call_quit_sync() for the synchronous, blocking version of this method.
 */
void
mpris_media_player2_call_quit (
    MprisMediaPlayer2 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Quit",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * mpris_media_player2_call_quit_finish:
 * @proxy: A #MprisMediaPlayer2Proxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mpris_media_player2_call_quit().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with mpris_media_player2_call_quit().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris_media_player2_call_quit_finish (
    MprisMediaPlayer2 *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris_media_player2_call_quit_sync:
 * @proxy: A #MprisMediaPlayer2Proxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2.Quit">Quit()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See mpris_media_player2_call_quit() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris_media_player2_call_quit_sync (
    MprisMediaPlayer2 *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Quit",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris_media_player2_call_raise:
 * @proxy: A #MprisMediaPlayer2Proxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2.Raise">Raise()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mpris_media_player2_call_raise_finish() to get the result of the operation.
 *
 * See mpris_media_player2_call_raise_sync() for the synchronous, blocking version of this method.
 */
void
mpris_media_player2_call_raise (
    MprisMediaPlayer2 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Raise",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * mpris_media_player2_call_raise_finish:
 * @proxy: A #MprisMediaPlayer2Proxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mpris_media_player2_call_raise().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with mpris_media_player2_call_raise().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris_media_player2_call_raise_finish (
    MprisMediaPlayer2 *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris_media_player2_call_raise_sync:
 * @proxy: A #MprisMediaPlayer2Proxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2.Raise">Raise()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See mpris_media_player2_call_raise() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris_media_player2_call_raise_sync (
    MprisMediaPlayer2 *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Raise",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris_media_player2_complete_quit:
 * @object: A #MprisMediaPlayer2.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mpris-MediaPlayer2.Quit">Quit()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
mpris_media_player2_complete_quit (
    MprisMediaPlayer2 *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * mpris_media_player2_complete_raise:
 * @object: A #MprisMediaPlayer2.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mpris-MediaPlayer2.Raise">Raise()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
mpris_media_player2_complete_raise (
    MprisMediaPlayer2 *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * MprisMediaPlayer2Proxy:
 *
 * The #MprisMediaPlayer2Proxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * MprisMediaPlayer2ProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #MprisMediaPlayer2Proxy.
 */

struct _MprisMediaPlayer2ProxyPrivate
{
  GData *qdata;
};

static void mpris_media_player2_proxy_iface_init (MprisMediaPlayer2Iface *iface);

G_DEFINE_TYPE_WITH_CODE (MprisMediaPlayer2Proxy, mpris_media_player2_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (MPRIS_TYPE_MEDIA_PLAYER2, mpris_media_player2_proxy_iface_init));

static void
mpris_media_player2_proxy_finalize (GObject *object)
{
  MprisMediaPlayer2Proxy *proxy = MPRIS_MEDIA_PLAYER2_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (mpris_media_player2_proxy_parent_class)->finalize (object);
}

static void
mpris_media_player2_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 5);
  info = _mpris_media_player2_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
mpris_media_player2_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  error = NULL;
  if (!g_dbus_proxy_call_finish (proxy, res, &error))
    {
      g_warning ("Error setting property `%s' on interface org.mpris.MediaPlayer2: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
}

static void
mpris_media_player2_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 5);
  info = _mpris_media_player2_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.mpris.MediaPlayer2", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) mpris_media_player2_proxy_set_property_cb, (gpointer) info);
  g_variant_unref (variant);
}

static void
mpris_media_player2_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_mpris_media_player2_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], MPRIS_TYPE_MEDIA_PLAYER2);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, MPRIS_TYPE_MEDIA_PLAYER2);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
mpris_media_player2_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  MprisMediaPlayer2Proxy *proxy = MPRIS_MEDIA_PLAYER2_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mpris_media_player2_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mpris_media_player2_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static gboolean 
mpris_media_player2_proxy_get_can_quit (MprisMediaPlayer2 *object)
{
  MprisMediaPlayer2Proxy *proxy = MPRIS_MEDIA_PLAYER2_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "CanQuit");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
mpris_media_player2_proxy_get_can_raise (MprisMediaPlayer2 *object)
{
  MprisMediaPlayer2Proxy *proxy = MPRIS_MEDIA_PLAYER2_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "CanRaise");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
mpris_media_player2_proxy_get_desktop_entry (MprisMediaPlayer2 *object)
{
  MprisMediaPlayer2Proxy *proxy = MPRIS_MEDIA_PLAYER2_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "DesktopEntry");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
mpris_media_player2_proxy_get_has_track_list (MprisMediaPlayer2 *object)
{
  MprisMediaPlayer2Proxy *proxy = MPRIS_MEDIA_PLAYER2_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "HasTrackList");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
mpris_media_player2_proxy_get_identity (MprisMediaPlayer2 *object)
{
  MprisMediaPlayer2Proxy *proxy = MPRIS_MEDIA_PLAYER2_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Identity");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static void
mpris_media_player2_proxy_init (MprisMediaPlayer2Proxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, MPRIS_TYPE_MEDIA_PLAYER2_PROXY, MprisMediaPlayer2ProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), mpris_media_player2_interface_info ());
}

static void
mpris_media_player2_proxy_class_init (MprisMediaPlayer2ProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (MprisMediaPlayer2ProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = mpris_media_player2_proxy_finalize;
  gobject_class->get_property = mpris_media_player2_proxy_get_property;
  gobject_class->set_property = mpris_media_player2_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = mpris_media_player2_proxy_g_signal;
  proxy_class->g_properties_changed = mpris_media_player2_proxy_g_properties_changed;


  mpris_media_player2_override_properties (gobject_class, 1);
}

static void
mpris_media_player2_proxy_iface_init (MprisMediaPlayer2Iface *iface)
{
  iface->get_can_quit = mpris_media_player2_proxy_get_can_quit;
  iface->get_can_raise = mpris_media_player2_proxy_get_can_raise;
  iface->get_desktop_entry = mpris_media_player2_proxy_get_desktop_entry;
  iface->get_has_track_list = mpris_media_player2_proxy_get_has_track_list;
  iface->get_identity = mpris_media_player2_proxy_get_identity;
}

/**
 * mpris_media_player2_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-mpris-MediaPlayer2.top_of_page">org.mpris.MediaPlayer2</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mpris_media_player2_proxy_new_finish() to get the result of the operation.
 *
 * See mpris_media_player2_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
mpris_media_player2_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (MPRIS_TYPE_MEDIA_PLAYER2_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.mpris.MediaPlayer2", NULL);
}

/**
 * mpris_media_player2_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mpris_media_player2_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with mpris_media_player2_proxy_new().
 *
 * Returns: (transfer full) (type MprisMediaPlayer2Proxy): The constructed proxy object or %NULL if @error is set.
 */
MprisMediaPlayer2 *
mpris_media_player2_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return MPRIS_MEDIA_PLAYER2 (ret);
  else
    return NULL;
}

/**
 * mpris_media_player2_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-mpris-MediaPlayer2.top_of_page">org.mpris.MediaPlayer2</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See mpris_media_player2_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type MprisMediaPlayer2Proxy): The constructed proxy object or %NULL if @error is set.
 */
MprisMediaPlayer2 *
mpris_media_player2_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (MPRIS_TYPE_MEDIA_PLAYER2_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.mpris.MediaPlayer2", NULL);
  if (ret != NULL)
    return MPRIS_MEDIA_PLAYER2 (ret);
  else
    return NULL;
}


/**
 * mpris_media_player2_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like mpris_media_player2_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mpris_media_player2_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See mpris_media_player2_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
mpris_media_player2_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (MPRIS_TYPE_MEDIA_PLAYER2_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.mpris.MediaPlayer2", NULL);
}

/**
 * mpris_media_player2_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mpris_media_player2_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with mpris_media_player2_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type MprisMediaPlayer2Proxy): The constructed proxy object or %NULL if @error is set.
 */
MprisMediaPlayer2 *
mpris_media_player2_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return MPRIS_MEDIA_PLAYER2 (ret);
  else
    return NULL;
}

/**
 * mpris_media_player2_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like mpris_media_player2_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See mpris_media_player2_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type MprisMediaPlayer2Proxy): The constructed proxy object or %NULL if @error is set.
 */
MprisMediaPlayer2 *
mpris_media_player2_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (MPRIS_TYPE_MEDIA_PLAYER2_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.mpris.MediaPlayer2", NULL);
  if (ret != NULL)
    return MPRIS_MEDIA_PLAYER2 (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * MprisMediaPlayer2Skeleton:
 *
 * The #MprisMediaPlayer2Skeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * MprisMediaPlayer2SkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #MprisMediaPlayer2Skeleton.
 */

struct _MprisMediaPlayer2SkeletonPrivate
{
  GValueArray *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex *lock;
};

static void
_mpris_media_player2_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = {0};
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], MPRIS_TYPE_MEDIA_PLAYER2);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, MPRIS_TYPE_MEDIA_PLAYER2);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_mpris_media_player2_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mpris_media_player2_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_mpris_media_player2_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mpris_media_player2_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _mpris_media_player2_skeleton_vtable =
{
  _mpris_media_player2_skeleton_handle_method_call,
  _mpris_media_player2_skeleton_handle_get_property,
  _mpris_media_player2_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
mpris_media_player2_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return mpris_media_player2_interface_info ();
}

static GDBusInterfaceVTable *
mpris_media_player2_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_mpris_media_player2_skeleton_vtable;
}

static GVariant *
mpris_media_player2_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_mpris_media_player2_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _mpris_media_player2_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _mpris_media_player2_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _mpris_media_player2_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.mpris.MediaPlayer2", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _mpris_media_player2_emit_changed (gpointer user_data);

static void
mpris_media_player2_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (skeleton->priv->lock);

  if (emit_changed)
    _mpris_media_player2_emit_changed (skeleton);
}

static void mpris_media_player2_skeleton_iface_init (MprisMediaPlayer2Iface *iface);
G_DEFINE_TYPE_WITH_CODE (MprisMediaPlayer2Skeleton, mpris_media_player2_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (MPRIS_TYPE_MEDIA_PLAYER2, mpris_media_player2_skeleton_iface_init));

static void
mpris_media_player2_skeleton_finalize (GObject *object)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (object);
  g_value_array_free (skeleton->priv->properties);
  g_list_foreach (skeleton->priv->changed_properties, (GFunc) _changed_property_free, NULL);
  g_list_free (skeleton->priv->changed_properties);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  if (skeleton->priv->context != NULL)
    g_main_context_unref (skeleton->priv->context);
  g_mutex_free (skeleton->priv->lock);
  G_OBJECT_CLASS (mpris_media_player2_skeleton_parent_class)->finalize (object);
}

static void
mpris_media_player2_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 5);
  g_mutex_lock (skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties->values[prop_id - 1], value);
  g_mutex_unlock (skeleton->priv->lock);
}

static gboolean
_mpris_media_player2_emit_changed (gpointer user_data)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties->values[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      g_dbus_connection_emit_signal (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                     NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                     "org.freedesktop.DBus.Properties",
                                     "PropertiesChanged",
                                     g_variant_new ("(sa{sv}as)",
                                                    "org.mpris.MediaPlayer2",
                                                    &builder, &invalidated_builder),
                                     NULL);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_foreach (skeleton->priv->changed_properties, (GFunc) _changed_property_free, NULL);
  g_list_free (skeleton->priv->changed_properties);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (skeleton->priv->lock);
  return FALSE;
}

static void
_mpris_media_player2_schedule_emit_changed (MprisMediaPlayer2Skeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
mpris_media_player2_skeleton_notify (GObject      *object,
  GParamSpec *pspec)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (object);
  g_mutex_lock (skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _mpris_media_player2_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (skeleton->priv->lock);
}

static void
mpris_media_player2_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 5);
  g_mutex_lock (skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties->values[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _mpris_media_player2_schedule_emit_changed (skeleton, _mpris_media_player2_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties->values[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties->values[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
mpris_media_player2_skeleton_init (MprisMediaPlayer2Skeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, MPRIS_TYPE_MEDIA_PLAYER2_SKELETON, MprisMediaPlayer2SkeletonPrivate);
  skeleton->priv->lock = g_mutex_new ();
  skeleton->priv->context = g_main_context_get_thread_default ();
  if (skeleton->priv->context != NULL)
    g_main_context_ref (skeleton->priv->context);
  skeleton->priv->properties = g_value_array_new (5);
  g_value_array_append (skeleton->priv->properties, NULL);
  g_value_init (&skeleton->priv->properties->values[0], G_TYPE_BOOLEAN);
  g_value_array_append (skeleton->priv->properties, NULL);
  g_value_init (&skeleton->priv->properties->values[1], G_TYPE_BOOLEAN);
  g_value_array_append (skeleton->priv->properties, NULL);
  g_value_init (&skeleton->priv->properties->values[2], G_TYPE_STRING);
  g_value_array_append (skeleton->priv->properties, NULL);
  g_value_init (&skeleton->priv->properties->values[3], G_TYPE_BOOLEAN);
  g_value_array_append (skeleton->priv->properties, NULL);
  g_value_init (&skeleton->priv->properties->values[4], G_TYPE_STRING);
}

static gboolean 
mpris_media_player2_skeleton_get_can_quit (MprisMediaPlayer2 *object)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (object);
  gboolean value;
  g_mutex_lock (skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties->values[0]));
  g_mutex_unlock (skeleton->priv->lock);
  return value;
}

static gboolean 
mpris_media_player2_skeleton_get_can_raise (MprisMediaPlayer2 *object)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (object);
  gboolean value;
  g_mutex_lock (skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties->values[1]));
  g_mutex_unlock (skeleton->priv->lock);
  return value;
}

static const gchar *
mpris_media_player2_skeleton_get_desktop_entry (MprisMediaPlayer2 *object)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (object);
  const gchar *value;
  g_mutex_lock (skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties->values[2]));
  g_mutex_unlock (skeleton->priv->lock);
  return value;
}

static gboolean 
mpris_media_player2_skeleton_get_has_track_list (MprisMediaPlayer2 *object)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (object);
  gboolean value;
  g_mutex_lock (skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties->values[3]));
  g_mutex_unlock (skeleton->priv->lock);
  return value;
}

static const gchar *
mpris_media_player2_skeleton_get_identity (MprisMediaPlayer2 *object)
{
  MprisMediaPlayer2Skeleton *skeleton = MPRIS_MEDIA_PLAYER2_SKELETON (object);
  const gchar *value;
  g_mutex_lock (skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties->values[4]));
  g_mutex_unlock (skeleton->priv->lock);
  return value;
}

static void
mpris_media_player2_skeleton_class_init (MprisMediaPlayer2SkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (MprisMediaPlayer2SkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = mpris_media_player2_skeleton_finalize;
  gobject_class->get_property = mpris_media_player2_skeleton_get_property;
  gobject_class->set_property = mpris_media_player2_skeleton_set_property;
  gobject_class->notify       = mpris_media_player2_skeleton_notify;


  mpris_media_player2_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = mpris_media_player2_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = mpris_media_player2_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = mpris_media_player2_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = mpris_media_player2_skeleton_dbus_interface_get_vtable;
}

static void
mpris_media_player2_skeleton_iface_init (MprisMediaPlayer2Iface *iface)
{
  iface->get_can_quit = mpris_media_player2_skeleton_get_can_quit;
  iface->get_can_raise = mpris_media_player2_skeleton_get_can_raise;
  iface->get_desktop_entry = mpris_media_player2_skeleton_get_desktop_entry;
  iface->get_has_track_list = mpris_media_player2_skeleton_get_has_track_list;
  iface->get_identity = mpris_media_player2_skeleton_get_identity;
}

/**
 * mpris_media_player2_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-mpris-MediaPlayer2.top_of_page">org.mpris.MediaPlayer2</link>.
 *
 * Returns: (transfer full) (type MprisMediaPlayer2Skeleton): The skeleton object.
 */
MprisMediaPlayer2 *
mpris_media_player2_skeleton_new (void)
{
  return MPRIS_MEDIA_PLAYER2 (g_object_new (MPRIS_TYPE_MEDIA_PLAYER2_SKELETON, NULL));
}

