include ../../../mk/rules.mk
include ../../../mk/init.mk

presetsdir = $(pkgdatadir)/paranormal/Presets

OBJECTIVE_DATA = \
	nenolod_-_purple_flower.pnv:$(presetsdir)	\
	nenolod_-_bumblebees.pnv:$(presetsdir)

include ../../../mk/objective.mk
