include ../../../mk/rules.mk
include ../../../mk/init.mk

presetsdir = $(pkgdatadir)/paranormal/Presets

OBJECTIVE_DATA = \
	nenolod_-_purple_flower.pnv:$(presetsdir)	\
	nenolod_-_bumblebees.pnv:$(presetsdir)		\
	nenolod_-_flying_into_pastels.pnv:$(presetsdir)	\
	nenolod_-_phosphor_flame.pnv:$(presetsdir)	\
	nenolod_-_psuedo_starfield.pnv:$(presetsdir)	\
	nenolod_-_quakingscope.pnv:$(presetsdir)	\
	nenolod_-_beatscope.pnv:$(presetsdir)		\
	nenolod_-_branchscope.pnv:$(presetsdir)		\
	nenolod_-_retroscope.pnv:$(presetsdir)		\
	nenolod_-_value_replace_fun.pnv:$(presetsdir)	\
	nenolod_-_rush.pnv:$(presetsdir)

include ../../../mk/objective.mk
