DATA = nazca_-_smoke_on_the_water.pnv		\
       nenolod_-_3d_wave.pnv			\
       nenolod_-_aquamarine_dream.pnv		\
       nenolod_-_purple_flower.pnv		\
       nenolod_-_bumblebees.pnv			\
       nenolod_-_flying_into_pastels.pnv	\
       nenolod_-_phosphor_flame.pnv		\
       nenolod_-_psuedo_starfield.pnv		\
       nenolod_-_quakingscope.pnv		\
       nenolod_-_beatscope.pnv			\
       nenolod_-_branchscope.pnv		\
       nenolod_-_retroscope.pnv			\
       nenolod_-_technicolour_nightmare.pnv	\
       nenolod_-_trapped.pnv			\
       nenolod_-_value_replace_fun.pnv		\
       nenolod_-_rush.pnv			\
       nenolod_-_worms.pnv			\
       nenolod_-_scopefun.pnv			\
       nenolod_-_smoke.pnv			\
       nenolod_-_swarm.pnv			\
       nenolod_-_interlaced.pnv			\
       nenolod_-_cubism.pnv			\
       nenolod_-_transform_fun.pnv		\
       nenolod_-_tunnel_vision.pnv		\
       nenolod_-_kaliedoscope.pnv		\
       nenolod_-_simple_yet_pretty.pnv		\
       nenolod_-_quasar.pnv			\
       aerdan_-_bloody_vortex.pnv		\
       aerdan_-_cloudscape.pnv			\
       aerdan_-_cloudscape2.pnv			\
       aerdan_-_dancing_snow.pnv		\
       aerdan_-_portal_to_hell.pnv		\
       aerdan_-_telestatic.pnv			\
       ticpu_-_colored_beat-o-scope.pnv	

include ../../../buildsys.mk

PACKAGE = audacious/paranormal/Presets
