SRCS = i_pcfg.c

STATIC_LIB_NOINST = libpcfg.a

include ../../../buildsys.mk
include ../../../extra.mk

noinst_HEADERS = i_pcfg.h

CFLAGS += $(PLUGIN_CFLAGS)
CPPFLAGS += $(PLUGIN_CPPFLAGS) $(GLIB_CFLAGS) -I../../..

