include ../mk/rules.mk
include ../mk/init.mk

SUBDIRS = $(INPUT_PLUGINS) \
	$(OUTPUT_PLUGINS) \
	$(EFFECT_PLUGINS) \
	$(VISUALIZATION_PLUGINS) \
	$(GENERAL_PLUGINS) \
	$(CONTAINER_PLUGINS)

include ../mk/objective.mk
