include ../extra.mk

SUBDIRS = ${INPUT_PLUGINS}		\
	  ${OUTPUT_PLUGINS}		\
	  ${EFFECT_PLUGINS}		\
	  ${VISUALIZATION_PLUGINS}	\
	  ${GENERAL_PLUGINS}		\
	  ${CONTAINER_PLUGINS}		\
	  ${TRANSPORT_PLUGINS}

include ../buildsys.mk
